### ISSUE TITLE
`vater sync` `git diff` fails

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#108]
```
control@control:~$ vater sync
Password:
Traceback (most recent call last):
  File "/home/control/vater/control-services/cli/vater.py", line 122, in <module>
    main()
  File "/home/control/vater/control-services/cli/vater.py", line 18, in main
    sync(c, p.args)
  File "/home/control/vater/control-services/cli/vater.py", line 41, in sync
    g.syncContentRepo()
  File "/home/control/vater/control-services/cli/gitea.py", line 89, in syncContentRepo
    self.__copyLatestContentRepo()
  File "/home/control/vater/control-services/cli/gitea.py", line 139, in __copyLatestContentRepo
    out += check_output(
  File "/usr/lib/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['sudo', 'git', 'diff', '--diff-filter=r', '--name-status', '--compact-summary', '--color', '--no-index', '/home/control/vater/control-services/data/gitea/git/rous', '/home/control/rous/']' returned non-zero exit status 1.
```

Commented out:

`gitea.py`
```
134         # Check to see if an old repo exists in gitea
135         p = Path(self.cfg['gitea']['content_repo_path'])
136         if p.exists():
137
138             # Display a diff of old repo and new repo
139             out += check_output(
140                 [
141                     'sudo', 'git', 'diff', '--diff-filter=r', '--name-status',
142                     '--compact-summary', '--color', '--no-index',
143                     self.cfg['gitea']['content_repo_path'],
144                     self.cfg['host']['content_dir_path']
145                 ],
146                 universal_newlines=True
147             )
148
```

This is supposed to print a nice message about what changes there were, but tends to miss the mark.

**Comment by uwardlaw** [comment]
Merged #85

**Comment by samanthapark413** [comment]
@uwardlaw `subprocess` calls `CalledProcessError` when the command it runs results in a non-zero exit status. `git diff` returns 1 when there are differences, not when there's an error. It returns 0 when there aren't differences.
If we use `subprocess.run` instead of `subprocess.check_output,` we can avoid the call to `CalledProcessError`.
`subprocess.run` returns a `CompletedProcess` which has `stdout` and `stderr ` fields. We can print the contents afterwards and add them to `out` as well.

**Comment by uwardlaw** [comment]
Nice find, I'd just want to know if we need to implement error handling ourselves / inspect for errors.

An error in `git diff` probably won't cause problems though so I wouldn't hold up on it. I suspect the program would fail during the `git clone` anyway, but I don't know if `diff` errors are a subset of `clone` errors..

**Comment by samanthapark413** [comment]
@uwardlaw At the very least, I can print `stderr `out every time, immediately after I print `stdout `so you can manually catch errors if need be.

**Comment by uwardlaw** [comment]
Getting the output right looks like a common problem based on this StackOverflow (question)[https://stackoverflow.com/questions/4380945/exclude-a-directory-from-git-diff]

**Comment by samanthapark413** [comment]
@uwardlaw Here's a solution related to the files in .gitignore: https://stackoverflow.com/questions/17820056/git-diff-doesnt-ignore-specified-files-in-gitignore

**Comment by samanthapark413** [comment]
A very small snippet of the overly-long` git diff `output:

```
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth0-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth0-001.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth1-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth1-001.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth10-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth11-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth12-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth13-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth14-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth2-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth2-001.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth3-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth4-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth5-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth6-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth7-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth8-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-eth9-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-unused0-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-unused0-001.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-unused1-000.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/10-unused1-001.link
A       /home/control/rous/isos/vyos/vyos-build/tools/dell/vep4600/99-default.link
A       /home/control/rous/isos/vyos/vyos-build/tools/get_latest_iso.py
A       /home/control/rous/isos/vyos/vyos-build/tools/gpl-header-template
A       /home/control/rous/isos/vyos/vyos-build/tools/run-qemu-image.sh
A       /home/control/rous/isos/vyos/vyos-build/tools/submod-mk
A       /home/control/rous/isos/vyos/vyos-build/tools/switch-remote
A       /home/control/rous/isos/vyos/vyos-build/tools/u-boot-spl.kwb
A       /home/control/rous/isos/vyos/vyos-build/tools/vendors_udev/64-vyos-SAF51003I-net.rules
A       /home/control/rous/isos/vyos/vyos-build/tools/vendors_udev/64-vyos-SAF51015I-net.rules
A       /home/control/rous/isos/vyos/vyos-build/vars/README.md
A       /home/control/rous/isos/vyos/vyos-build/vars/buildPackage.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/cloneAndBuild.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/getChangeSetPath.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/getGitBranchName.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/getGitRepoName.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/getGitRepoURL.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/getJenkinsfilePath.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/isCustomBuild.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/isPullRequest.groovy
A       /home/control/rous/isos/vyos/vyos-build/vars/setDescription.groovy
A       /home/control/rous/isos/vyos/vyos.iso.bak
A       /home/control/rous/terraform/.terraform/environment
A       /home/control/rous/terraform/.terraform/providers/registry.terraform.io/hashicorp/time/0.7.2/linux_amd64/terraform-provider-time_v0.7.2_x5
A       /home/control/rous/terraform/.terraform/providers/registry.terraform.io/hashicorp/vsphere/1.15.0/linux_amd64/terraform-provider-vsphere_v1.15.0_x4
A       /home/control/rous/terraform/.terraform.lock.hcl
A       /home/control/rous/terraform/terraform.tfstate.d/student01/terraform.tfstate
A       /home/control/rous/terraform/terraform.tfstate.d/student01/terraform.tfstate.backup
A       /home/control/rous/terraform/terraform.tfstate.d/student02/terraform.tfstate
A       /home/control/rous/terraform/terraform.tfstate.d/student02/terraform.tfstate.backup
A       /home/control/rous/tree.out
M       /home/control/vater/control-services/data/gitea/git/rous/vms/core/vyos-core-router/vyos-core-router.pkr.hcl
A       /home/control/rous/vms/core/vyos-core-router/vyos.iso
M       /home/control/vater/control-services/data/gitea/git/rous/vms/windows_fundamentals/vyos-fundamentals-router/vyos-fundamentals-router.pkr.hcl
A       /home/control/rous/vms/windows_fundamentals/vyos-fundamentals-router/vyos.iso
A       /home/control/rous/vms/windows_fundamentals/win2k19-AD/unattend/.autounattend.xml.swp
M       /home/control/vater/control-services/data/gitea/git/rous/vms/windows_fundamentals/win2k19-AD/unattend/autounattend.xml
D       /home/control/vater/control-services/data/gitea/git/rous/vms/windows_fundamentals/win2k19-AD/unattend/old_auto
A       /home/control/rous/vms/windows_fundamentals/win2k19-AD/unattend/old_auto.xml
warning: inexact rename detection was skipped due to too many files.
warning: you may want to set your diff.renameLimit variable to at least 65744 and retry the command.
```

**Comment by uwardlaw** [comment]
I read that, but the issue is our git ignore works already and those directories are not being tracked.

You can see what is being ignored with this : https://git-scm.com/docs/git-check-ignore

Anything listed should not appear in the diff

**Comment by samanthapark413** [comment]
Attempted to exclude directories/files with the solution you mentioned earlier (https://stackoverflow.com/questions/4380945/exclude-a-directory-from-git-diff). Just getting usage or syntax errors. 
I also tried combining all the `.gitignore` files into a single `.gitignore` in the git root directory. This didn't affect the output.
I also installed diff-so-fancy. Piping the `git diff` output to diff-so-fancy also did not affect the output. I am currently looking into diff-so-fancy options.

**Comment by samanthapark413** [comment]
`diff `will actually exclude. Implemented a solution that passes `diff `everything in the` .gitignore `file(s)

**Comment by samanthapark413** [comment]
The solution mentioned above won't suffice because `diff`'s exclude option is very limited. Will be running `diff `and using python to filter the output to exclude entries in the` .gitignore`(s)

**Comment by uwardlaw** [comment]
After looking through multiple resources for answers, we arrived at using this command to get the differences:

```
GIT_ALTERNATE_OBJECT_DIRECTORIES=.git/objects git diff-tree --compact-summary $(GIT_DIR=~/vater/control-services/data/gitea/git/rous/.git git rev-parse --verify HEAD) HEAD
```

References:
- [git diff-tree](https://git-scm.com/docs/git-diff-tree)
- [How to compare two local repositories](https://git.wiki.kernel.org/index.php/GitTips#How_to_compare_two_local_repositories)

**Comment by samanthapark413** [comment]
Previously, we discussed using `grep ` w/ the reverse option to filter the output of `git diff `. However, this is not a great solution because `git diff` takes ~30s given the inability to exclude directories/files in the` .gitignore` files.

My latest attempt (call `diff `and filter out `.gitignore` entries as well as untracked files), to be replaced by the solution above:

I created an entry for content repo `.gitignore` file paths in `vater/control-services/cli/config.py`:
` cfg['content_repo']['git_ignore_rel_paths'] = [ ".gitignore"]`

Then looped through the list of` .gitignore `files to compile a list of all the `.gitignore` entries (`cfg['content_repo']['git_ignore_entries']`) - removing any unnecessary characters and expanding any entries that had regex's:
`        entries = []
         for rel_path in cfg['content_repo']['git_ignore_rel_paths']:
             abs_path = cfg['host']['content_dir_path'] + rel_path
             with open(abs_path, 'r') as f:
                 for line in f:
                     if line[0] != '#' and line[0] != '\n':
                         start_of_path = abs_path.rsplit('/', 1)[0] + '/'
                          line = ((start_of_path + line)[:-1]).rstrip()
                         if line[len(line)-1] == '/':
                             entries.append(line[:-1])
                             line += "**"
                         if '*' in line:
                              entries = entries + glob.glob(line, recursive=True)
                              entries.append(line.replace("*", ""))
                          else:
                              entries.append(line)
          cfg['content_repo']['git_ignore_entries'] = entries`

In  `vater/control-services/cli/gitea.py` I ran a `diff`, and filtered its output so that it excluded all `.gitignore `entries and untracked files (obtained from `git status`):
            ` # Display a diff of old repo and new repo
              diff_output = run(
                  [
                      'sudo', 'diff', '--color',
                      '--recursive', '--brief',
                      self.cfg['gitea']['content_repo_path'],
                      self.cfg['host']['content_dir_path']
                  ],
                  stdout=PIPE, stderr=STDOUT, universal_newlines=True
              )

              # Run git status to enumerate untracked files
              git_status_output = run (
                  [
                      'sudo', 'git', 'status'
                  ],
                  stdout=PIPE, stderr=STDOUT
              )
 
              # Extract untracked files from git status output
              git_status_out = git_status_output.stdout.decode('utf-8')
              delim1 = '(use "git add <file>..." to include in what will be committed)'
              delim2 = 'no changes added to commit (use "git add" and/or "git commit -a")'
              index1 = git_status_out.find(delim1) + len(delim1)
              index2 = git_status_out.find(delim2)
              untracked_blob = git_status_out[index1:index2]
              untracked_blob = untracked_blob.lstrip().rstrip()
              untracked_files = untracked_blob.split('\n')
              for i, filename in enumerate(untracked_files):
                  untracked_files[i] = filename.lstrip().rstrip()
 
              # Filter .gitignore entries from diff results
              diff_results = diff_output.stdout.splitlines()
              temp = []
              files_to_remove = self.cfg['content_repo']['git_ignore_entries'] + untracked_files
             #print(files_to_remove)
              for entry in files_to_remove:
                  for result in diff_results:
                      edited_result = result.replace(": ", "/")
                      if entry not in edited_result:
                           temp.append(result)
                  diff_results = temp
                  temp = []
 
               formatted_results = '\n'.join(result for result in diff_results)
               out += formatted_results
               print(diff_output.stderr)
               print(formatted_results)`
