### ISSUE TITLE
`vater restart` attempts to access directories it doesn't have access to

### ISSUE THREAD

**Issue by samanthapark413** [uwardlaw/vater#123]
`vater restart` attempts to access directories not associated with user that ran it (e.g. directories in other users' home directories)

**Comment by samanthapark413** [comment]
`os.path.expanduser()` returns $HOME which is altered by sudo, so using the `getpass` module would be a better solution

**Comment by samanthapark413** [comment]
`config.py` should check to see if `vater` is being run with `sudo` before doing anything, and return gracefully with a warning to not run with `sudo`

**Comment by marissaeinhorn** [comment]
Need to verify if this was implemented

**Comment by uwardlaw** [comment]
@marissaeinhorn 

There was this in `config.py` ln 11-13.

```python
        if os.getuid() == 0:
            print("Please do not run with sudo")
            exit()
```

This code should probably be relocated to `vater.py` or the root problem should be solved (pun), which I can't identify anymore. At one point I believe there was a piece of code reliant on getting the current user and their home path, but `config.json` has those statically configured now...

I did a quick search for `os.`, `user`, and `path` and I can't find anything that would be reliant on the current user executing `vater`. That being said, using `sudo` should be discouraged for obvious security reasons. Any commands that need `sudo` use `sudo` directly in their call, so there should be no reason to use `sudo vater`.

**Comment by uwardlaw** [comment]
Disregard, I think I found the affected code in `parser.py`:

```python
        self.homedir = "/home/" + getpass.getuser()

        self.__parser.add_argument(
            '-c', '--configPath',
            help =  'The json conifguration file',
            default = self.homedir + '/vater/control-services/config.json'
        )
```
