### ISSUE TITLE
Chain Packer Builders

### ISSUE THREAD

**Issue by rylagek** [uwardlaw/vater#130]
Update packer files with [chained builders](https://medium.com/swlh/chaining-machine-image-builds-with-packer-b6fd99e35049) for easier packer testing and development.
- https://www.packer.io/docs/builders

**Builders in focus:**
- [x] [VSphere-ISO](https://www.packer.io/docs/builders/vsphere/vsphere-iso) (builds to `vCenter`)
- [x] [VirtualBox-ISO](https://www.packer.io/docs/builders/virtualbox/iso) (builds directly to `VirtualBox`)
- [x] [Vagrant-ISO](https://www.packer.io/docs/builders/vagrant) (builds `Vagrant` boxes)
- [x] [VMWare-ISO](https://www.packer.io/docs/builders/vmware/iso) (builds directly to `VMWare`)

**Comment by rylagek** [comment]
Each builder also needs a proper source - we should make generic source blocks to work with each builder we need

**Comment by marissaeinhorn** [comment]
[pack_everything](https://github.com/rylagek/pack_everything)
