### ISSUE TITLE
Packer Template for `Ops Network - Internal: Server 2K19 DC`

### ISSUE THREAD

**Issue by rylagek** [uwardlaw/vater#133]
### Implementing #99 
- [x] PowerShell Remote System Administration Tools (RSAT) Module installed
- Command `Add-WindowsFeature RSAT-AD-PowerShell`
- [x] Services (DNS, DHCP, NTP)
- [x] [Winlogbeats](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation-configuration.html) deployed
- Command: `PowerShell.exe -ExecutionPolicy UnRestricted -File .\install-service-winlogbeat.ps1`
~~Needs to have [fake user accounts](https://github.com/lorentzenman/youzer) generated~~ 
~~Needs fake machine accounts~~
- Just change the 3 in the while loop, to the desired amount of machines you want to create
- Powershell Script:
```
import-module ActiveDirectory
$computername = "workstation"

while ($i -ne 3){
    $newname = $computername + $i
    $newname
    New-ADComputer -Name $newname -SamAccountName $newname -Path "OU=Workstations,OU=LAB,DC=lab,DC=local"
    $i ++
}
```

**Comment by marissaeinhorn** [comment]
Please make sure this powershell module is included `Install-WindowsFeature -name AD-Domain-Services -IncludeManagementTools`

**Comment by rylagek** [comment]
Correction - I had a typo in the NTP config. Only DNS needs to be configured post-deployment

**Comment by rylagek** [comment]
[This](https://thebackroomtech.com/2021/03/10/how-to-install-ntp-server-on-windows-server-2019/) gave the `ps` commands to set up basic ntp

**Comment by rylagek** [comment]
Static ip set - template complete. Fake users and machines must be done with post deployment
