### ISSUE TITLE
Include course ID in addition to class number for all applicable variables

### ISSUE THREAD

**Issue by marissaeinhorn** [uwardlaw/vater#157]
Potential point of conflict brought up in demo 12/16.  CWO and UCWT don't have unique class numbers so we must include a course id as well in folders/variables/switch names

- [ ] Alter the placeholder values in the `Create Class` `arguments` parameter in `semaphore.py` to reflect any changes to the class ID structure 
- [ ] Add a check for correctness in the `createClasss.yml` that confirms the `UCWT` or `CWO` identifier is set

**Comment by uwardlaw** [comment]
I think the easiest way to handle this is to add a `U` for `UCWT` and `C` for `CWO`, such that `U21012` is class `21012` in `UCWT`.

**Comment by uwardlaw** [comment]
Remarked as requirement because we cannot field `VATER` if there are class conflicts for resource naming.

**Comment by marissaeinhorn** [comment]
`class[0] != "U" and class[0] != "C"
ansible variables [article](https://www.mydailytutorials.com/working-ansible-variables-conditionals/)

**Comment by marissaeinhorn** [comment]
Successfully builds classes.  Implemented with #89 in rous/iss89.  Cannot test create range because rous/iss82 was not merged with main yet
