### ISSUE TITLE
Build terraform file for DCO enclave

### ISSUE THREAD

**Issue by marissaeinhorn** [uwardlaw/vater#179]
- [x] Define network map for UCWT DCO enclave
- [x] Write .tf file with vms, snapshots and networks
- [x] Build `group_vars` file with all variables

**Comment by rylagek** [comment]
@marissaeinhorn 
List of all template names for DCO TM to be found in vsphere template tab folder

Folder Name: `dcoTM`

Templates:
`effects_kali`

`inet_rtr`

`onion_sensor`

`win_10_admin`
`win_10_wkst1`
`win_10_wkst2`
`win_10_wkst3`
`build_windows2019`

`win_10_dco`
`onion_dco`

**Comment by marissaeinhorn** [comment]
Variables in terraform file 
```
variable "dco_router_template_name" {}

variable "dco_effects_template_name" {}

variable "dco_onion_sensor_template_name" {}
variable "dco_win10_wkst1_template_name" {}
variable "dco_win10_wkst2_template_name" {}
variable "dco_win10_wkst3_template_name" {}
variable "dco_win10_admin_template_name" {}
variable "dco_win2019_dc_template_name" {}

variable "dco_win10_student_template_name" {}
variable "dco_onion_template_name" {}

variable "dco_attack_switch_name" {}
variable "dco_attack_port_group_name" {}

variable "dco_domain_switch_name" {}
variable "dco_domain_port_group_name" {}

variable "dco_analysis_switch_name" {}
variable "dco_analysis_port_group_name" {}
```

**Comment by marissaeinhorn** [comment]
Currently missing `onion_sensor`, `onion_dco` and `effects_kali` templates
