### ISSUE TITLE
Create virtual networks/port-groups

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#63]
- Create the `vcenter` `virtual switches`
   - `class#_student#_switch00`
   - `class#_student#_switch01`
   - `class#_student#_switch02`
   - `class#_student#_switch03`
   - `class#_student#_switch04` 
- Create `port groups` attached to `virtual switches`
   - `class#_student#_net00`
   - `class#_student#_net01`
   - `class#_student#_net02`
   - `class#_student#_net03`
   - `class#_student#_net04` 

- Where `#` in `class#` is the number assigned to the class (e.g. `class21024`)
- Where `#` in `student#` is the number assigned to the student in the class (e.g. `student04`)

**Comment by marissaeinhorn** [comment]
- [ ] research if port groups need dedicated vswitch or if they can share
