### ISSUE TITLE
Create Packer `Fundamental Enclave` configuration for `Windows 2019 - Services`

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#65]
Service suggestions
- FTP
- DNS
- IIS

Needs to include some services that are not DC related.

**Comment by rylagek** [comment]
Services can be configured via scripts (`.ps1`) in the `scripts` folder or potentially additions to the answer file `autounattend.xml`

Currently blocked by issue uwardlaw/vater#98

**Comment by uwardlaw** [comment]
No longer being built
