### ISSUE TITLE
Create packer configuration for `Fundamental Enclave` `Windows 10 Domain Joined - Student`

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#66]
This configuration should have accounts set up for student use

**Comment by marissaeinhorn** [comment]
Terraform requires winrm to be enabled for windows customization

**Comment by marissaeinhorn** [comment]
- Terraform requires the most recent version of vmware tools be installed to configure vms during deployment

**Comment by uwardlaw** [comment]
Found the `windows8.flp` in the `VMWare Tools` [downloads](https://customerconnect.vmware.com/downloads/details?downloadGroup=VMTOOLS1135&productId=1073&rPId=74478) section. For the `11.3.5` version the download is called `VMware Tools packages for Windows`. Once the file is unzipped, the path to the file is `floppies/windows8.flp`.

**Comment by rylagek** [comment]
Successful build without windows updates in 38 min. With new design, `windows8.flp` is not required, but `VMware Tools exe` is required.

**Comment by rylagek** [comment]
Configuration still needs customized:

Requirements for terraform
- [ ] Hostname
- [ ] Default User
- [ ] Default Password
- [ ] Disable IPv6
- [ ] Enable Local Administrator account
- [ ] Standard Admin Password
 ----------------------------------------
Waiting on additional requirements and specifications via issue uwardlaw/vater#69

**Comment by uwardlaw** [comment]
No longer being built
