### ISSUE TITLE
Create Packer configuration for `Fundamental Enclave` `Windows 2019 - Active Directory`

### ISSUE THREAD

**Issue by uwardlaw** [uwardlaw/vater#68]
`Windows Server 2019` running `Active Directory`
- Variety of users and accounts

**Comment by rylagek** [comment]
Building off of the successful box spin up for Windows 10:

Changes in `2k19.pkr.hcl`
- `vm_guest_os_type`
- `os_iso_path`

Changes in `vsphere.pkr.hcl`
- source name from `win_10` to `win_2019`

Changes in `autounattend.xml`
- entire file replaced for windows server 2019 specific
- https://www.windowsafg.com/server2019.html - used to generate answer files for windows

**Comment by rylagek** [comment]
Using Windows 10 `autounattend.xml` when working with a different windows OS can cause windows setup to show No OS available

**Comment by rylagek** [comment]
Most answer files for windows are designed to work with trial ISO's. Using the vcenter hosted ISO would require the product key for that ISO

__Solution to pursue:__
Change from using hosted ISO to a trial ISO download link

**Comment by uwardlaw** [comment]
No longer being built
