### ISSUE TITLE
Create snapshots for deployed VMs

### ISSUE THREAD

**Issue by marissaeinhorn** [uwardlaw/vater#82]
Configure terraform to take snapshot of VM after deployment.  Terraform deployment is time intensive (5+ min) and would bust time requirements for TM/PC reversion (2 min).  Additional code block in terraform .tf file to take snapshot, insert ansible/semaphore playbook/button to revert vm vs rebuild from scratch.  

Considerations
- instructors may avoid semaphore and revert snapshots in vsphere
- doesn't violate IAC principles snapshot only persists for life of the class

**Comment by marissaeinhorn** [comment]
Consideration 
- research how much additional storage snapshots require

**Comment by uwardlaw** [comment]
This is an item we guaranteed during meeting, moves to requirement from enhancement

**Comment by marissaeinhorn** [comment]
added `vsphere_virtual_machine_snapshot` resource to terraform file.  Changes currently untested

**Comment by marissaeinhorn** [comment]
`createRange` executes with the following error 

```
TASK [Apply for student01] *****************************************************
fatal: [192.168.100.1]: FAILED! =>
msg: |-
The task includes an option with an undefined variable. The error was: 'intialSnapshotName' is undefined
```
