### ISSUE TITLE
Packer `Windows Server 2019` Core Issue - Need to Setup to Run via Trial ISO link

### ISSUE THREAD

**Issue by rylagek** [uwardlaw/vater#98]
Most answer files for windows are designed to work with trial ISO's. Using the vcenter hosted ISO would require the product key for that ISO

__Solution to pursue:__
Change from using hosted ISO to a trial ISO download link

_Originally posted by @rylagek in https://github.com/uwardlaw/vater/issues/68#issuecomment-975857496_

**Comment by rylagek** [comment]
Windows trial ISOs are protected downloads, we have to have the file stored already. Suggesting adding an ISOs folder to the rous structure via issue #106

**Comment by comeste10** [comment]
@rylagek @uwardlaw isn't the idea that we'll have all the ISOs and applications in a local vSphere data store? Maybe I'm misunderstanding what you mean by adding it to ROUS

**Comment by rylagek** [comment]
@comeste10 yes, that is the current way to have it work. However, that creates dependency on vSphere. If we want to create a more agnostic product we need to use a file structure that isn't virtualization product dependent. Short term, vSphere datastores are fine but long term we want to have everything quickly preconfigured anywhere - for example, setting up local labs for students via vboxmanage or vagrant. A more agnostic file structure would also limit any dev roadblocks caused by a need for contractor actions (like moving files for us). Depending on specific datastores is more likely to break packer files

**Comment by comeste10** [comment]
I think it's reasonable to optimize for VMWare at the moment as long as we keep track of our dependencies that'd need to be addressed if we shift to another virtualization platform

**Comment by rylagek** [comment]
I'm happy with that. Giving @uwardlaw the steps we need to have that happen with server 2k19 for tomorrow

**Comment by comeste10** [comment]
My packer example references the VMware ds on ducknet

**Comment by rylagek** [comment]
Yes, we have windows 10 completely running in that manner referencing the ds for ISOs. The changes that I know remain for 2k19 include:
- [ ] download and add `trial iso` to ds
- [ ] update `os_iso_path` var in `win2k19.auto.pkrvars.hcl`
- [ ] test build to verify answer file

Might need to
- [ ] remove win 10 specific scripts
(but I haven't looked at that too much)

**Comment by rylagek** [comment]
`Windows server 2019` builds w/o updates in 19 min - artifacts are saved via the formate `[datastore] buildName/filename`

**Comment by rylagek** [comment]
Closing as the generic builds are complete with no issue
